Borderline1/WhiteBoardApp

client/app.js, script/encrypt-heroku-auth-token.js, server/index.js
=> Live cursors are live

client/App.css, client/CollinsExampleWithNotes.js, client/app.js, client/components/SideBar.js, client/components/tools/circle.js, client/components/tools/index.js, client/socket.js, package-lock.json, package.json, public/style.css, server/index.js
=> Canvas gone

client/app.js, client/components/tools/circle.js, server/index.js
=> Circle form

client/app.js, client/components/SideBar.js
=> Tool color

server/index.js, server/socket.js
=> intervals fixed

client/app.js, client/components/SideBar.js, client/components/tools/circle.js, client/components/tools/rectangle.js
=> circle and rect working with click drag creation

client/app.js, client/components/tools/textBox.js
=> Removed unnecessary functions

client/app.js, client/components/tools/picker.js, client/components/tools/rectangle.js
=> picking can now drag, also small fixes for rectangle control

client/app.js, server/socket.js
=> Fixing socket updates- and not interfereing wit hDB

client/app.js, client/components/tools/textBox.js
=> Text box working sans cursor position

client/app.js, client/components/tools/circle.js, client/components/tools/line.js, client/components/tools/rectangle.js, client/components/tools/triangle.js
Added strokes to basic shapes, and made delete button conditionally render, not for N-gon though.
=> Added strokes to basic shapes, and made delete button conditionally render

client/app.js, client/components/tools/circle.js, client/components/tools/line.js, client/components/tools/polygon.js, client/components/tools/rectangle.js, client/components/tools/textBox.js, client/components/tools/triangle.js, public/style.css
=> Adjust buttons

client/components/tools/line.js, public/style.css
=> Add line adjustButtons dynamic changes

client/app.js, client/components/tools/circle.js, client/components/tools/iframe.js, client/components/tools/picker.js
Lasso can select multiple objects. Also indicates what it will select. next step is to make updating multiple object positions simultaneously a thing.
=> Lasso is lassoing.

client/app.js, client/components/ColorWheel.js, client/components/SideBar.js, client/components/tools/circle.js, client/components/tools/line.js, client/components/tools/polygon.js, client/components/tools/rectangle.js, client/components/tools/triangle.js, public/style.css
=> Color wheel

client/app.js, client/components/tools/picker.js, server/socket.js
=> Lasso copy Paste, now with multiple item dragging, delete still to come

client/app.js, client/components/tools/circle.js
=> Lasso copy paste -fixed induced bug while changing formats of variables

client/components/tools/line.js, client/components/tools/rectangle.js, public/style.css
=> Fix line width/height and rect adjust functionality

client/components/tools/line.js, client/components/tools/polygon.js, client/components/tools/rectangle.js, client/components/tools/textBox.js, client/components/tools/triangle.js
=> Add changes to adjustButtons to work across tools

client/app.js, client/components/tools/triangle.js, server/index.js, server/socket.js
=> fixes to lasso bug

client/components/ToolButton.js, client/components/tools/index.js, client/components/tools/rectangle.js, client/components/tools/rightTriangle.js, client/components/tools/textBox.js, public/style.css
=> Right triangle

public/style.css
=> Add hover effect to element buttons

client/components/SideBar.js, client/components/ToolButton.js, client/components/tools/rightTriangle.js
=> Sidebar tools branch

client/components/tools/triangle.js
=> Triangle now flips upside down during create/change

client/components/tools/image.js, client/components/tools/line.js, client/components/tools/rectangle.js, client/components/tools/rightTriangle.js, client/components/tools/textBox.js, client/components/tools/triangle.js
=> Add minor clean-up, removed a console.log

client/components/SideBar.js, client/components/tools/spline.js, public/index.html, public/style.css
=> Bug fixing for family night -spline has rotate and delete buttons

client/components/tools/index.js
=> Add positioning changes to tool menu

client/app.js, package-lock.json, package.json
=> More bug fixing - Hotkeys, Must NPM install

client/app.js
=> fixed bug with hotkeys

client/components/tools/triangle.js
=> Add classnames to triangle inputs
